### ISSUE TITLE
Rename path parameters to item_lookup_field

### ISSUE THREAD

**Issue by otibsa** [pyeve/eve-swagger#18]
``` python
people = {
    'item_lookup_field': 'name',
    'item_title': 'person',
    'schema': {...}
}
```

Currently the path parameters are named like `/people/{personId}`. To me it would seem more logical to name the parameter after the field name that is used for lookup, i.e. `/people/{name}`. 

Without a custom `item_lookup_field` that would result in `/people/{_id}` though...

**Comment by otibsa** [comment]
Another thing: having the `item_lookup_field` as the path parameter makes it clear what the index/key of the resource is. 
Without that, there is no correlation between the path parameter (`personId`) and the fields that are shown in the response (`name`, `address`, `birthdate`, `social_security_number`, ...)

I think this is related to issue #2.

**Comment by mkapuza** [comment]
I agree that this is a bug. Right now eve-swagger does not take into consideration the functionality within eve to provide an alternative lookup (i.e. anything other than the objectId).

Here is the code: https://github.com/pyeve/eve-swagger/blob/master/eve_swagger/objects.py#L99.

@otibsa's solution seems to make sense and you could have it fall back to the current `title.lower() + 'Id'` implementation if a custom `item_lookup_field` is not specified.

@nicolaiarocci I am happy to resolve this, but have not contributed to this project before. Let me know what your preference is. Another option would be to allow one to specify a `name` parameter that overrides this more explicitly. Either way it should be a pretty straightforward fix.

**Comment by nicolaiarocci** [comment]
@mkapuza I like your implementation plan. Go for it.
