### ISSUE TITLE
Import Swagger to Eve

### ISSUE THREAD

**Issue by tyomo4ka** [pyeve/eve-swagger#43]
Converting Eve to Swagger is cool.
But it would be even cooler to support Swagger natively. 

I found it's a little bit cumbersome to work with Eve when you go with API design first approach.

If you use services like APIMATIC or SwaggerHub, you can design API there and then produce machine readable config like swagger. It would be  nice if I can import it in Eve somehow, so I don't need to sync changes manually every time.

Of course I can design using Eve, but if I need to collaborate with other people it becomes problematic.

Connexxion is implementing this approach btw https://github.com/zalando/connexion

**Comment by nicolaiarocci** [comment]
I agree. This has been on my list for a very long time but never managed to get around. If you check https://www.patreon.com/nicolaiarocci you can see it listed among other things I'd like to have a chance to work on :)
