### ISSUE TITLE
Force 'https' schema only

### ISSUE THREAD

**Issue by bomb-on** [pyeve/eve-swagger#47]
I would like to force my Swagger UI to use `https` only. I tried to update my Swagger definition:

```python
add_documentation({
    'schemes': ['https'],
})
```
but in my Swagger UI I can still see a drop-down menu with both `http` and `https`.

Can I do this by updating my definition or should I handle it "manually" in my Swagger UI?

**Comment by jim8786453** [comment]
I'm not the developer of this module, but I just sent a pull request with a change that would allow you to do what you want, see https://github.com/pyeve/eve-swagger/pull/46.

I'm not familiar with the code base so what I've done might not be good, but maybe keep an eye on that pull request to see if it gets merged or not (if not I'll too need a solution to this issue).

**Comment by bomb-on** [comment]
Alright, thanks a lot!
