### ISSUE TITLE
If-Match header required when concurrency control is disabled

### ISSUE THREAD

**Issue by silver8ack** [pyeve/eve-swagger#49]
Swagger UI will not allow PUT/PATCH/DELETE without an If-Match header, even when concurrency control is disabled in the API.

In my settings for my api I have the following:
```
IF_MATCH = False
ENFORCE_IF_MATCH = False 
```

I have also tried removing the header from X_HEADERS:
```
X_HEADERS = ['Authorization', 'Content-Type', 'Accept']
```

I have verified that I can PUT/PATCH/DELETE objects via the REST API, but the swagger ui will not allow the 'Try it now' option without supplying an If-Match header.

**Comment by nicolaiarocci** [comment]
I am not sure wether this is a SwaggerUI or eve-swagger issue... did you investigate that?
