### ISSUE TITLE
How to add auth request headers?

### ISSUE THREAD

**Issue by luiscoms** [pyeve/eve-swagger#51]

**Comment by luiscoms** [comment]
Any answer for this question?

**Comment by nicolaiarocci** [comment]
What do you mean by 'how to add auth request headers'? To the swagger/openapi docs?

**Comment by luiscoms** [comment]
My API has Basic Auth token, so I want to pass header through swagger ui

**Comment by JoveYu** [comment]
because `securityDefinitions` and `security` is not implemented, I use this code 
```python
SWAGGER_EXT = {
    'securityDefinitions': {
        'basicAuth': {
            'type': 'basic'
        }
    },
    'security': [
        {'basicAuth':[]}
    ],
}
add_documentation(SWAGGER_EXT)
```

**Comment by JoveYu** [comment]
#86
