### ISSUE TITLE
add support for swagger schema example field

### ISSUE THREAD

**Issue by thomasleveil** [pyeve/eve-swagger#59]
See https://swagger.io/docs/specification/2-0/adding-examples/

The description field is [already supported](https://github.com/pyeve/eve-swagger#description-fields-on-the-swagger-docs), it would be nice to also support the `example` field in schema. This would make swagger-ui provide ready to use data in requests.

**Comment by nicolaiarocci** [comment]
This looks like a rather trivial implementation and I agree, it would be useful. Feel free to submit a PR for it!

**Comment by thomasleveil** [comment]
@nicolaiarocci I noticed that when using either `description` or `example` in python-eve, Cerberus complains about those unknown fields. Should the fix be on python-eve or should it be on the Cerberus side?

**Comment by nicolaiarocci** [comment]
As reported in the README:

> NOTE: As with the description, the field TRANSPARENT_SCHEMA_RULES must be enabled in your settings.py, otherwise the Cerberus library will display an error about "unknown field 'example' for field[yourFieldName]".
