### ISSUE TITLE
Swagged Editor reports error on generated JSON

### ISSUE THREAD

**Issue by samsantiago** [pyeve/eve-swagger#62]
Swagger Online Editor, [http://editor2.swagger.io](http://editor2.swagger.io)  generates error on JSON generated.

 Swagger Error
Not a valid parameter definition

Jump to line 616
Details
 Object
code:  "ONE_OF_MISSING"
 params: Array [0]
message:  "Not a valid parameter definition"
 path: Array [2]
0:  "parameters"
1:  "business__id"
schemaId:  "http://swagger.io/v2/schema.json#"
 inner: Array [2]
 0: Object
code:  "OBJECT_MISSING_REQUIRED_PROPERTY"
 params: Array [1]
message:  "Missing required property: schema"
 path: Array [2]
0:  "parameters"
1:  "business__id"
 1: Object
code:  "ONE_OF_MISSING"
 params: Array [0]
message:  "Data does not match any schemas from 'oneOf'"
 path: Array [2]
 inner: Array [4]
level: 900
type:  "Swagger Error"

Line 616 is in the "parameters:" definition area.  Each parameter defined generated same error.

**business__id**:
    in: path
    name: businessId
    required: true
    description: ''
    example: ''
    type: string
    format: objectid

business__id is referenced in this path definition and the parameter line is flagged with same error:

patch:
      summary: Updates a business document
      responses:
        '200':
          description: business document updated successfully
      **parameters**:
        - $ref: '#/parameters/business__id'
        - in: body
          name: business
          required: true
          schema:
            $ref: '#/definitions/business'
        - in: header
          name: If-Match
          description: Current value of the _etag field
          required: true
          type: string
      tags:
        - business

**Comment by bash77** [comment]
comment string 84 and 117 in objects.py:

```
  # example = rd['schema'][lookup_field].get('example') or ''
  ...
  # p['example'] = example
```

**Comment by samosaara** [comment]
I found out, that the path parameters need to be defined at the path level, not at the individual methods. Instead of 
```yaml
  '/desenho/{desenhoId}':
    put:
      summary: Replaces a Desenho document
      responses:
        '200':
          description: Desenho document replaced successfully
      parameters:
        - $ref: '#/parameters/Desenho__id' # <------- NOT HERE!!!
        - in: body
          name: Desenho
          required: true
          schema:
            $ref: '#/definitions/Desenho'
```
this:
```yaml
  '/desenho/{desenhoId}':
    parameters:
      - $ref: '#/parameters/Desenho__id' # <------- HERE INSTEAD
    put:
      summary: Replaces a Desenho document
      responses:
        '200':
          description: Desenho document replaced successfully
      parameters:
        - in: body
          name: Desenho
          required: true
          schema:
            $ref: '#/definitions/Desenho'
```
But I really believe this is a issue with eve-swagger itself right?
_Necroposting intensifies._
