### ISSUE TITLE
Custom resource urls for relationships with regular expressions should display only the label

### ISSUE THREAD

**Issue by rmlopes** [pyeve/eve-swagger#66]
Like in the [eve-docs](https://github.com/charlesflynn/eve-docs) extension, only the label should be in the docs for custom resource urls on related data. For instance,

> /model1/<regex("[a-f0-9]{24}"):model1_id>/model2

in the docs should be:

> /model1/model1_id/model2

**Comment by nicolaiarocci** [comment]
Agreed. Feel free to submit a PR I will be happy to review it.
