### ISSUE TITLE
Basic authentication not obeyed

### ISSUE THREAD

**Issue by checkaayush** [pyeve/eve-swagger#76]
I have added following Flask routes with authentication enabled. Authenticate class is defined appropriately. Basic auth working on all endpoints including /docs but when I access /static/index.html directly, basic auth doesn't work. 

What am I missing here?

```
app = Eve(__name__, static_folder='static', auth=Authenticate)

@app.route('/docs')
@utils.requires_auth
def docs():
    return redirect('/static/index.html', code=301)


@app.route('/')
@utils.requires_auth
def index():
    return send_from_directory('static', 'index.html')
```

**Comment by JoveYu** [comment]
because `securityDefinitions` and `security` is not implemented, I use this code 
```python
SWAGGER_EXT = {
    'securityDefinitions': {
        'basicAuth': {
            'type': 'basic'
        }
    },
    'security': [
        {'basicAuth':[]}
    ],
}
add_documentation(SWAGGER_EXT)
```

**Comment by JoveYu** [comment]
the master branch now use swagger3.0, and can auto generate auth docs #86
