### ISSUE TITLE
Swagger-UI py-eve basic authentication

### ISSUE THREAD

**Issue by kkuehl** [pyeve/eve-swagger#92]
I have enabled BasicAuth in py-eve which works properly.
I have also just installed eve-swagger which also mostly works.
If I use the Try It Out button,
Then perform Execute, it is obviously missing my authorization header.
https://swagger.io/docs/specification/authentication/basic-authentication/
Shows how to configure it normally, just not sure how to do it through eve-swagger.

Thanks in advance!

**Comment by Ziul** [comment]
Any updates about it?

**Comment by luiscoms** [comment]
I still interested about it
