### ISSUE TITLE
Cut new release to expose _compile_docs

### ISSUE THREAD

**Issue by jlane9** [pyeve/eve-swagger#93]
The dynamic swagger documentation was split from index_json into its own function, however there hasn't been a release since this change was made last year. So far I'm getting by installing via github, but an official release would be nicer. 

This is the function:
https://github.com/pyeve/eve-swagger/blob/89adbd1ee1c94ed8eab1c432d130f8ba23719061/eve_swagger/swagger.py#L60

I'm building support to have https://github.com/rochacbruno/flasgger/pull/316 (serves Swagger UI) consume this generated swagger at runtime and display swagger docs.

**Comment by rmlopes** [comment]
Hi @jlane9, to serve the UI there is a flask extension that works fine with eve-swagger out of the box: [flask_swagger_ui](https://pypi.org/project/flask-swagger-ui/)
