### ISSUE TITLE
URL_PREFIX is not included in the server url

### ISSUE THREAD

**Issue by AnthonyCaetano** [pyeve/eve-swagger#94]
current master adds the API_VERSION path segment to the url, but it doesn't add the URL_PREFIX

**Comment by FaraSeer** [comment]
@nicolaiarocci  could you reopen this issue?
I have the same problems.
For now it is not possible to make any 'Try is out' requests.

I have the following configuration:
URL_PREFIX = "api"
API_VERSION = "v1"
And requests must contain '/api' in their path, but they doesn't:
<img src="https://user-images.githubusercontent.com/8999527/118290878-970f4880-b4df-11eb-9e44-4326665bdfb9.png" width="30%" height="30%">
<img src="https://user-images.githubusercontent.com/8999527/118290941-aa221880-b4df-11eb-858e-7ca2e69415a8.png" width="90%" height="90%">
