### ISSUE TITLE
No name 'get_swagger_blueprint' in module 'eve_swagger'

### ISSUE THREAD

**Issue by maulikdoshi82** [pyeve/eve-swagger#99]
Getting above issue on vsc for 
from eve_swagger import get_swagger_blueprint, add_documentation

I do see add_documentation method but not get_swagger_blueprint inside  eve-swagger.swagger. 

Installed today using pip3 install eve-swagger

**Comment by tiwariav** [comment]
https://github.com/pyeve/eve-swagger/issues/99

Following the documentation on PyPI, instead of `get_swagger_blueprint`, import `swagger` and use it as following.

```
from eve import Eve
from eve_swagger import swagger, add_documentation

app = Eve()
app.register_blueprint(swagger)
```

**Comment by rmlopes** [comment]
PyPI has not been updated yet. If not installing from github source, you should follow PyPI instructions. If installing from source then the repository docs apply.
